---
- hosts: all
  tasks:
    - name: Copy file and run the script
      #become: yes    (this will not work, you need to set this on play/task)
      become: yes
      #become_method: dzdo
      #become_user: root
      copy:
        src: /var/dzdo.txt
        dest: /tmp/dzdo.txt
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
