- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
      environment:
        PYTHONPATH: /var/lib/awx/venv/ansible/lib/python2.7/site-packages

