- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
      environment:
        PYTHONPATH: /var/lib/awx/venv/awx/lib64/python3.6/site-packages/


