- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
      environment:
        PYTHONPATH: /opt/rh/rh-python36/root/lib/python3.6/site-packages/


