---
- name: Test Reboot
  hosts: all
  tasks:
    - name: ping
      ping:
    - name: Reboot
      reboot:
        reboot_timeout: 600
        #post_reboot_delay: 60
        test_command: whoami
    - name: ping
      ping:    
