---

- hosts: all
  remote_user: testuser

  tasks:
  - name: Syncing demo directory ...
    synchronize:
     src: ./READMME.md
     dest: ./ansible-tower-samples/sync.yml
     delete: yes
     recursive: yes
