---

- hosts: all
  remote_user: ec2-user

  tasks:
  - name: Syncing demo directory ...
    synchronize:
     src: /var/lib/awx/projects/ansible-examples
     dest: /home/ec2-user
     delete: yes
     recursive: yes
