---
- name: testasync
  hosts: all
  tasks:
  - name: Reset invocation_exec variable.
    set_fact:
      invocation_exec:
        results: []

  - name: Execute Node Setup
    async: 600
    #become: 'yes'
    #become_user: root
    command: bash -c 'sleep 60 && exit 0'
    poll: 0
    register: invocation_exec
    when: 'not ansible_check_mode '
    with_items:
    - '1'

  - name: Await completion
    async_status: jid={{ item.ansible_job_id }}
    #become: 'yes'
    #become_user: root
    delay: 10
    register: invocation_exec_results
    retries: 60
    until: invocation_exec_results.finished
    when: not ansible_check_mode
    with_items:
    - '{{ invocation_exec.results }}'
