---
- hosts: all
  tasks:
   - name: sleep for 5400 seconds and continue with play
     wait_for:
       timeout: 5400
     delegate_to: localhost
   - name: Hello Message
     debug:
       msg: "Hello World!"
