---
- name: Test windows
  hosts: all
  tasks:
    - name: ping
      win_ping:
    - name: Ensure user bob is present
      win_user:
        name: bob
        password: B0bP4ssw0rd
        state: present
        groups:
          - Users
